const name= "Haliuka";
let age= 25;
let hobby= "Learning languages";
const gender= "Female";
let employedStatus= "Unemployed";
let hungerLevel = "Starving";
let mood = "bored";
console.log("Name: " + name);
console.log("Age: " + age);
console.log("Hobby: " + hobby);
console.log("Gender: " + gender);
console.log("Employment Status: " + employedStatus);
console.log("Hunger Level: " + hungerLevel + " 💀❗️");
console.log("Please take a break, I wanna eat something!!");
console.log("Mood: Bored " + "(" + (mood==="bored") + ")");
console.log("Imagining myself eating something...");
console.log("om nom nom nom 🍛 eating..");
hungerLevel = "Full";
console.log("Hunger Level: " + hungerLevel);
mood = "Happy";
console.log("Mood: " + mood);
console.log(mood!=="bored");
console.log("-------------------------------");
console.log("Basghiin ugsun daalgavar");
const car = "car";
const twelve = 12;
const boolean = true;
const notCar = true;
const notTwelve = true;
// alert("ene odoo yaaj ajillaad bganbe");

console.log("-------------------------------");
let number = 495;
let thirdDigit = number % 10;
let secondDigit = Math.floor((number/10)%10);
let firstDigit = Math.floor(number/100);
console.log(firstDigit + secondDigit + thirdDigit);